### PR TITLE
Foo

### PR DESCRIPTION
**Pull request by max99x**
Change description would go here.

---
This change is [Reviewable](https://reviewable.io/reviews/max99x/test-repo-for-review/1)

### CODE REVIEW

**Comment by max99x** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[new-foo, line 3 at r1](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYQEcfTUwmfgaqH4hf:-KyYQEcfTUwmfgaqH4hg:b-wflta) ([raw file](https://github.com/max99x/test-repo-for-review/blob/c3269641f27a3c20973cf4534a850d3a0b253d64/new-foo#L3)):*
> ```
> This is a foo.
> Bar is the name.
> It is somewhat quux.
> ```

Hey me,  this doesn't sound right. Change it plz. kthxbye

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYQWogbn2ENwCOXQN4:-KyYQWogbn2ENwCOXQN5:bkmdhsv) ([raw file](https://github.com/max99x/test-repo-for-review/blob/c3269641f27a3c20973cf4534a850d3a0b253d64/README.md#L6)):*
> ```Markdown
> Some new lines
> Some new lines
> Some new lines
> ```

Too many lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by max99x** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[new-foo, line 3 at r1](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYQEcfTUwmfgaqH4hf:-KyYS_ImnbXVdOGqXA4t:b-896fix) ([raw file](https://github.com/max99x/test-repo-for-review/blob/c3269641f27a3c20973cf4534a850d3a0b253d64/new-foo#L3)):*
<details><summary><i>Previously, max99x (Max Shawabkeh) wrote…</i></summary><blockquote>

Hey me,  this doesn't sound right. Change it plz. kthxbye
</blockquote></details>

Done.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYQWogbn2ENwCOXQN4:-KyYSaQgLgKdj68wsDrR:baxek4y) ([raw file](https://github.com/max99x/test-repo-for-review/blob/c3269641f27a3c20973cf4534a850d3a0b253d64/README.md#L6)):*
<details><summary><i>Previously, max99x (Max Shawabkeh) wrote…</i></summary><blockquote>

Too many lines.
</blockquote></details>

This better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by max99x** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[new-foo, line 3 at r1](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYQEcfTUwmfgaqH4hf:-KyYT1w4sz92G1LYs6H0:b-896fix) ([raw file](https://github.com/max99x/test-repo-for-review/blob/c3269641f27a3c20973cf4534a850d3a0b253d64/new-foo#L3)):*
<details><summary><i>Previously, max99x (Max Shawabkeh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by max99x** [comment]
Reviewed 1 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by max99x** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by alwang328** [comment]
*[README.md, line 5 at r2](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYi9VWeoWWsWiSjSFc:-KyYi9VWeoWWsWiSjSFd:bb64gh0) ([raw file](https://github.com/max99x/test-repo-for-review/blob/b874dccc17df43de62ffe408da8474dd99a6c363/README.md#L5)):*
> ```Markdown
> 
> Some new lines
> Some new lines
> ```

The new line is the same as the old one!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by alwang328** [comment]
*[new-foo, line 3 at r2](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYhdHl_0w6dhue-v5V:-KyYhdHl_0w6dhue-v5W:b-45lc7d) ([raw file](https://github.com/max99x/test-repo-for-review/blob/b874dccc17df43de62ffe408da8474dd99a6c363/new-foo#L3)):*
> ```
> This is a foo.
> Bar is the name.
> It is very quux.
> ```

I'm not familiar with quux. Why do we need one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by max99x** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[new-foo, line 3 at r2](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYhdHl_0w6dhue-v5V:-KyYi_WdIkl1z4fywquk:b-fag52y) ([raw file](https://github.com/max99x/test-repo-for-review/blob/b874dccc17df43de62ffe408da8474dd99a6c363/new-foo#L3)):*
<details><summary><i>Previously, alwang328 wrote…</i></summary><blockquote>

I'm not familiar with quux. Why do we need one?
</blockquote></details>

Cause it's the new hotness. No one uses single-u quxes anymore.

---

*[README.md, line 5 at r2](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYi9VWeoWWsWiSjSFc:-KyYiiE8sai5Y9OFMDbK:b-dh1onh) ([raw file](https://github.com/max99x/test-repo-for-review/blob/b874dccc17df43de62ffe408da8474dd99a6c363/README.md#L5)):*
<details><summary><i>Previously, alwang328 wrote…</i></summary><blockquote>

The new line is the same as the old one!
</blockquote></details>

The first revision had none!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Comment by alwang328** [comment]
*[README.md, line 5 at r2](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1#-KyYi9VWeoWWsWiSjSFc:-KyYjL630YFjiVUfk50j:b-pcdfdj) ([raw file](https://github.com/max99x/test-repo-for-review/blob/b874dccc17df43de62ffe408da8474dd99a6c363/README.md#L5)):*
<details><summary><i>Previously, max99x (Max Shawabkeh) wrote…</i></summary><blockquote>

The first revision had none!
</blockquote></details>

Tru dat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/max99x/test-repo-for-review/1)*

**Pull request merged**
